-- Customer 360 source ingestion script for SQL Server
-- Purpose:
-- 1. Define separate source-side tables for POS, CRM, and CSV uploads
-- 2. Keep the same column layout across all three source tables
-- 3. Load those source tables into the landing table
--
-- Assumption:
-- - Source operational database is SQL Server
-- - CSV files from users are first loaded into dbo.csv_customer_360_source
-- - Landing table remains a separate integration-layer object

IF OBJECT_ID('dbo.pos_customer_360_source', 'U') IS NOT NULL
    DROP TABLE dbo.pos_customer_360_source;
GO

IF OBJECT_ID('dbo.crm_customer_360_source', 'U') IS NOT NULL
    DROP TABLE dbo.crm_customer_360_source;
GO

IF OBJECT_ID('dbo.csv_customer_360_source', 'U') IS NOT NULL
    DROP TABLE dbo.csv_customer_360_source;
GO

IF OBJECT_ID('dbo.customer_360_landing', 'U') IS NOT NULL
    DROP TABLE dbo.customer_360_landing;
GO

CREATE TABLE dbo.pos_customer_360_source (
    source_load_id        BIGINT IDENTITY(1,1) PRIMARY KEY,
    batch_id              VARCHAR(100) NOT NULL,
    record_source         VARCHAR(20) NOT NULL DEFAULT 'POS',
    record_type           VARCHAR(30) NOT NULL,
    source_file_name      VARCHAR(255) NULL,
    source_row_number     BIGINT NULL,
    source_record_id      VARCHAR(100) NULL,
    customer_id           VARCHAR(100) NULL,
    source_customer_id    VARCHAR(100) NULL,
    first_name            VARCHAR(100) NULL,
    middle_name           VARCHAR(100) NULL,
    last_name             VARCHAR(100) NULL,
    dob                   DATE NULL,
    gender                VARCHAR(20) NULL,
    ssn                   VARCHAR(50) NULL,
    email_address         VARCHAR(255) NULL,
    phone_number          VARCHAR(25) NULL,
    phone_type            VARCHAR(20) NULL,
    is_verified           BIT NULL,
    opt_in_marketing      BIT NULL,
    address_type          VARCHAR(20) NULL,
    address_line_1        VARCHAR(200) NULL,
    address_line_2        VARCHAR(200) NULL,
    city                  VARCHAR(100) NULL,
    state_code            VARCHAR(10) NULL,
    postal_code           VARCHAR(20) NULL,
    country_code          VARCHAR(3) NULL,
    order_id              VARCHAR(100) NULL,
    channel               VARCHAR(30) NULL,
    payment_type          VARCHAR(30) NULL,
    status                VARCHAR(20) NULL,
    gross_amount          DECIMAL(12,2) NULL,
    discount_amount       DECIMAL(12,2) NULL,
    net_amount            DECIMAL(12,2) NULL,
    interaction_type      VARCHAR(50) NULL,
    campaign_id           VARCHAR(50) NULL,
    event_ts              DATETIME2 NULL,
    ingest_ts             DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    raw_payload           VARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.crm_customer_360_source (
    source_load_id        BIGINT IDENTITY(1,1) PRIMARY KEY,
    batch_id              VARCHAR(100) NOT NULL,
    record_source         VARCHAR(20) NOT NULL DEFAULT 'CRM',
    record_type           VARCHAR(30) NOT NULL,
    source_file_name      VARCHAR(255) NULL,
    source_row_number     BIGINT NULL,
    source_record_id      VARCHAR(100) NULL,
    customer_id           VARCHAR(100) NULL,
    source_customer_id    VARCHAR(100) NULL,
    first_name            VARCHAR(100) NULL,
    middle_name           VARCHAR(100) NULL,
    last_name             VARCHAR(100) NULL,
    dob                   DATE NULL,
    gender                VARCHAR(20) NULL,
    ssn                   VARCHAR(50) NULL,
    email_address         VARCHAR(255) NULL,
    phone_number          VARCHAR(25) NULL,
    phone_type            VARCHAR(20) NULL,
    is_verified           BIT NULL,
    opt_in_marketing      BIT NULL,
    address_type          VARCHAR(20) NULL,
    address_line_1        VARCHAR(200) NULL,
    address_line_2        VARCHAR(200) NULL,
    city                  VARCHAR(100) NULL,
    state_code            VARCHAR(10) NULL,
    postal_code           VARCHAR(20) NULL,
    country_code          VARCHAR(3) NULL,
    order_id              VARCHAR(100) NULL,
    channel               VARCHAR(30) NULL,
    payment_type          VARCHAR(30) NULL,
    status                VARCHAR(20) NULL,
    gross_amount          DECIMAL(12,2) NULL,
    discount_amount       DECIMAL(12,2) NULL,
    net_amount            DECIMAL(12,2) NULL,
    interaction_type      VARCHAR(50) NULL,
    campaign_id           VARCHAR(50) NULL,
    event_ts              DATETIME2 NULL,
    ingest_ts             DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    raw_payload           VARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.csv_customer_360_source (
    source_load_id        BIGINT IDENTITY(1,1) PRIMARY KEY,
    batch_id              VARCHAR(100) NOT NULL,
    record_source         VARCHAR(20) NOT NULL DEFAULT 'CSV',
    record_type           VARCHAR(30) NOT NULL,
    source_file_name      VARCHAR(255) NULL,
    source_row_number     BIGINT NULL,
    source_record_id      VARCHAR(100) NULL,
    customer_id           VARCHAR(100) NULL,
    source_customer_id    VARCHAR(100) NULL,
    first_name            VARCHAR(100) NULL,
    middle_name           VARCHAR(100) NULL,
    last_name             VARCHAR(100) NULL,
    dob                   DATE NULL,
    gender                VARCHAR(20) NULL,
    ssn                   VARCHAR(50) NULL,
    email_address         VARCHAR(255) NULL,
    phone_number          VARCHAR(25) NULL,
    phone_type            VARCHAR(20) NULL,
    is_verified           BIT NULL,
    opt_in_marketing      BIT NULL,
    address_type          VARCHAR(20) NULL,
    address_line_1        VARCHAR(200) NULL,
    address_line_2        VARCHAR(200) NULL,
    city                  VARCHAR(100) NULL,
    state_code            VARCHAR(10) NULL,
    postal_code           VARCHAR(20) NULL,
    country_code          VARCHAR(3) NULL,
    order_id              VARCHAR(100) NULL,
    channel               VARCHAR(30) NULL,
    payment_type          VARCHAR(30) NULL,
    status                VARCHAR(20) NULL,
    gross_amount          DECIMAL(12,2) NULL,
    discount_amount       DECIMAL(12,2) NULL,
    net_amount            DECIMAL(12,2) NULL,
    interaction_type      VARCHAR(50) NULL,
    campaign_id           VARCHAR(50) NULL,
    event_ts              DATETIME2 NULL,
    ingest_ts             DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    raw_payload           VARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.customer_360_landing (
    landing_id            BIGINT IDENTITY(1,1) PRIMARY KEY,
    batch_id              VARCHAR(100) NOT NULL,
    record_source         VARCHAR(20) NOT NULL,
    record_type           VARCHAR(30) NOT NULL,
    source_file_name      VARCHAR(255) NULL,
    source_row_number     BIGINT NULL,
    source_record_id      VARCHAR(100) NULL,
    customer_id           VARCHAR(100) NULL,
    source_customer_id    VARCHAR(100) NULL,
    first_name            VARCHAR(100) NULL,
    middle_name           VARCHAR(100) NULL,
    last_name             VARCHAR(100) NULL,
    dob                   DATE NULL,
    gender                VARCHAR(20) NULL,
    ssn                   VARCHAR(50) NULL,
    email_address         VARCHAR(255) NULL,
    phone_number          VARCHAR(25) NULL,
    phone_type            VARCHAR(20) NULL,
    is_verified           BIT NULL,
    opt_in_marketing      BIT NULL,
    address_type          VARCHAR(20) NULL,
    address_line_1        VARCHAR(200) NULL,
    address_line_2        VARCHAR(200) NULL,
    city                  VARCHAR(100) NULL,
    state_code            VARCHAR(10) NULL,
    postal_code           VARCHAR(20) NULL,
    country_code          VARCHAR(3) NULL,
    order_id              VARCHAR(100) NULL,
    channel               VARCHAR(30) NULL,
    payment_type          VARCHAR(30) NULL,
    status                VARCHAR(20) NULL,
    gross_amount          DECIMAL(12,2) NULL,
    discount_amount       DECIMAL(12,2) NULL,
    net_amount            DECIMAL(12,2) NULL,
    interaction_type      VARCHAR(50) NULL,
    campaign_id           VARCHAR(50) NULL,
    event_ts              DATETIME2 NULL,
    ingest_ts             DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    raw_payload           VARCHAR(MAX) NULL
);
GO

INSERT INTO dbo.customer_360_landing (
    batch_id,
    record_source,
    record_type,
    source_file_name,
    source_row_number,
    source_record_id,
    customer_id,
    source_customer_id,
    first_name,
    middle_name,
    last_name,
    dob,
    gender,
    ssn,
    email_address,
    phone_number,
    phone_type,
    is_verified,
    opt_in_marketing,
    address_type,
    address_line_1,
    address_line_2,
    city,
    state_code,
    postal_code,
    country_code,
    order_id,
    channel,
    payment_type,
    status,
    gross_amount,
    discount_amount,
    net_amount,
    interaction_type,
    campaign_id,
    event_ts,
    ingest_ts,
    raw_payload
)
SELECT
    batch_id,
    record_source,
    record_type,
    source_file_name,
    source_row_number,
    source_record_id,
    customer_id,
    source_customer_id,
    first_name,
    middle_name,
    last_name,
    dob,
    gender,
    ssn,
    email_address,
    phone_number,
    phone_type,
    is_verified,
    opt_in_marketing,
    address_type,
    address_line_1,
    address_line_2,
    city,
    state_code,
    postal_code,
    country_code,
    order_id,
    channel,
    payment_type,
    status,
    gross_amount,
    discount_amount,
    net_amount,
    interaction_type,
    campaign_id,
    event_ts,
    ingest_ts,
    raw_payload
FROM dbo.pos_customer_360_source;
GO

INSERT INTO dbo.customer_360_landing (
    batch_id,
    record_source,
    record_type,
    source_file_name,
    source_row_number,
    source_record_id,
    customer_id,
    source_customer_id,
    first_name,
    middle_name,
    last_name,
    dob,
    gender,
    ssn,
    email_address,
    phone_number,
    phone_type,
    is_verified,
    opt_in_marketing,
    address_type,
    address_line_1,
    address_line_2,
    city,
    state_code,
    postal_code,
    country_code,
    order_id,
    channel,
    payment_type,
    status,
    gross_amount,
    discount_amount,
    net_amount,
    interaction_type,
    campaign_id,
    event_ts,
    ingest_ts,
    raw_payload
)
SELECT
    batch_id,
    record_source,
    record_type,
    source_file_name,
    source_row_number,
    source_record_id,
    customer_id,
    source_customer_id,
    first_name,
    middle_name,
    last_name,
    dob,
    gender,
    ssn,
    email_address,
    phone_number,
    phone_type,
    is_verified,
    opt_in_marketing,
    address_type,
    address_line_1,
    address_line_2,
    city,
    state_code,
    postal_code,
    country_code,
    order_id,
    channel,
    payment_type,
    status,
    gross_amount,
    discount_amount,
    net_amount,
    interaction_type,
    campaign_id,
    event_ts,
    ingest_ts,
    raw_payload
FROM dbo.crm_customer_360_source;
GO

INSERT INTO dbo.customer_360_landing (
    batch_id,
    record_source,
    record_type,
    source_file_name,
    source_row_number,
    source_record_id,
    customer_id,
    source_customer_id,
    first_name,
    middle_name,
    last_name,
    dob,
    gender,
    ssn,
    email_address,
    phone_number,
    phone_type,
    is_verified,
    opt_in_marketing,
    address_type,
    address_line_1,
    address_line_2,
    city,
    state_code,
    postal_code,
    country_code,
    order_id,
    channel,
    payment_type,
    status,
    gross_amount,
    discount_amount,
    net_amount,
    interaction_type,
    campaign_id,
    event_ts,
    ingest_ts,
    raw_payload
)
SELECT
    batch_id,
    record_source,
    record_type,
    source_file_name,
    source_row_number,
    source_record_id,
    customer_id,
    source_customer_id,
    first_name,
    middle_name,
    last_name,
    dob,
    gender,
    ssn,
    email_address,
    phone_number,
    phone_type,
    is_verified,
    opt_in_marketing,
    address_type,
    address_line_1,
    address_line_2,
    city,
    state_code,
    postal_code,
    country_code,
    order_id,
    channel,
    payment_type,
    status,
    gross_amount,
    discount_amount,
    net_amount,
    interaction_type,
    campaign_id,
    event_ts,
    ingest_ts,
    raw_payload
FROM dbo.csv_customer_360_source;
GO

-- After customer_360_landing is populated, downstream ETL can split data into:
-- dim_customer
-- dim_customer_address
-- dim_customer_phone
-- dim_customer_email
-- fact_order
-- fact_customer_interaction
